from snakemake.utils import min_version
min_version("6.0")

configfile: "config/config.json"
pepfile: config["pepfile"]

include: "rules/comparison.smk"

def get_genomes(wildcards):
    out = []
    for sample in pep.sample_table.sample_name.tolist():
        out.append(rules.anvio_estimate_metabolism.output[0].format(genome=sample))
        out.append(rules.microbeannotator_estimate_metabolism.output[0].format(genome=sample))
        out.append(rules.kofam_estimate_metabolism.output[0].format(genome=sample))
        out.append(rules.anvio_export_functions_no_huerestic.output[0].format(genome=sample))
        out.append(rules.microbeannotator_refined.output[0].format(genome=sample))
        out.append(rules.kofamscan_refined.output[0].format(genome=sample)),
        out.append(rules.dram.output[0].format(genome=sample)),
        out.append(rules.anvio_setup_kegg_stray_kofams.output[0].format(genome=sample)),
        out.append(rules.anvio_export_functions_stray.output[0].format(genome=sample)),
        out.append(rules.anvio_export_functions.output[0].format(genome=sample)),
        out.append(rules.anvio_estimate_metabolism_stray.output[0].format(genome=sample)),
        out.append(rules.microbeannotator_estimate_metabolism_refined.output[0].format(genome=sample))
    return out

rule all:
    input:get_genomes
