from snakemake.utils import min_version
min_version("6.0")

include: "rules/annotation.smk"
include: "rules/comparison.smk"
include: "rules/sample_selection.smk"

rule all:
    input: 
        rules.download_genomes_refseq.output,
        rules.download_genomes_genbank.output
