pep_version: 2.0.0
sample_table: ""
subsample_table: ""
sample_modifiers:
  append:
    raw_data: "" #Change for run
  duplicate:
    sample_type: genomes
  derive:
    attributes: [genomes]
    sources:
      fasta: "{raw_data}/{subsample}*.fa"
