pep_version: 2.0.0
sample_table: "results/gtdb_sample_table.tsv"
sample_modifiers:
  append:
    raw_data: "resources/data/" #Change for run
  duplicate:
    sample_type: genomes
  derive:
    attributes: [genomes]
    sources:
      fasta: "{raw_data}/{subsample}*.fa"
